---
section: deploy
title: Implementierung und Upgrade von ONTAP Tools
entries:
- title: Implementierungs-Workflow für neue Benutzer von ONTAP Tools für VMware vSphere
  url: "/deploy/concept_installation_workflow_for_new_users.html"
- title: Implementierungs-Workflow für bestehende Benutzer von ONTAP-Tools
  url: "/deploy/concept_installation_workflow_for_existing_users_of_ontap_tools.html"
- title: Implementierungs-Modus von VMware Cloud Foundation für ONTAP Tools
  url: "/deploy/vmware_cloud_foundation_mode_deployment.html"
- title: ONTAP-Tools Schnellstartanleitung
  url: "/qsg.html"
- title: Anforderungen für die Implementierung der ONTAP Tools
  entries:
  - title: Port-Anforderungen für ONTAP-Tools
    url: "/deploy/reference_port_requirements_for_vsc.html"
  - title: Platz- und Dimensionierungsanforderungen für die ONTAP-Tools
    url: "/deploy/concept_space_and_sizing_requirements_for_ontap_tools_for_vmware_vsphere.html"
  - title: Unterstützte Storage-Systeme, Lizenzen und Applikationen für die ONTAP
      Tools
    url: "/deploy/concept_supported_storage_system_and_applications.html"
  - title: Überlegungen bei der Implementierung von ONTAP Tools
    url: "/deploy/reference_considerations_for_deploying_ontap_tools_for_vmware_vsphere.html"
- title: Implementierung von ONTAP Tools
  entries:
  - title: So laden Sie ONTAP-Tools herunter
    url: "/deploy/concept_how_to_download_ontap_tools.html"
  - title: So implementieren Sie ONTAP-Tools
    url: "/deploy/task_deploy_ontap_tools.html"
  - title: Aktivieren Sie VASA Provider zur Konfiguration von virtuellen Datastores
    url: "/deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html"
  - title: Installieren Sie das NFS VAAI Plug-in
    url: "/deploy/task_install_the_nfs_vaai_plug_in.html"
  - title: Löschen Sie die heruntergeladenen Plug-in-Pakete von vSphere im Cache
    url: "/deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html"
- title: Upgrade von ONTAP-Tools
  entries:
  - title: Upgraden auf die aktuelle Version von ONTAP-Tools
    url: "/deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html"
  - title: Aktualisieren Sie Den Storage Replication Adapter
    url: "/deploy/task_upgrade_storage_replication_adapter.html"
